name: build-and-test
on:
  push:
  pull_request:
    branches:
      - 'release'
      - 'main'


env:
  DOTNET_VERSION: '6.0.400'
  RSYNC_PASSWORD: ${{ secrets.PASSWORD }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and Deploy
        shell: bash
        run: |
          cd ./source
          dotnet tool restore
          dotnet docfx build
          rsync -avh ./_site ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }}:${{ secrets.DEST_PATH }}
