name: build-and-test
on:
  push:
  pull_request:
    branches:
      - 'release'
      - 'main'


env:
  DOTNET_VERSION: '6.0.400'
  RSYNC_PASSWORD: ${{ secrets.PASSWORD }}
  RSYNC_USERNAME: ${{ secrets.USERNAME }}
  RSYNC_HOSTNAME: ${{ secrets.HOSTNAME }}
  RSYNC_DEST_PATH: ${{ secrets.DEST_PATH }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and Deploy
        shell: bash
        run: |
          cd ./source
          dotnet tool restore
          dotnet docfx build
          echo "${{ env.RSYNC_PASSWORD }}" >> $RSYNC_PASSWORD
          echo "${{ env.RSYNC_USERNAME}}@${{env.RSYNC_HOSTNAME}}:${{env.DEST_PATH}}"
          rsync -avh ./_site ${{ env.RSYNC_USERNAME }}@${{ env.RSYNC_HOSTNAME }}:${{ env.DEST_PATH }}
