name: build-and-test
on:
  push:
  pull_request:
    branches:
      - 'release'
      - 'main'


env:
  DOTNET_VERSION: '6.0.400'



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Create ssh directory
        shell: bash
        run: sudo mkdir ~/.ssh

      - name: Create known hosts file
        shell: bash
        run: sudo touch ~/.ssh/known_hosts

      - name: Write Known Hosts
        shell: bash
        env:
          KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: sudo echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts

      - name: Build and Deploy
        shell: bash
        env:
          RSYNC_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          DEST_PATH: ${{ secrets.DEST_PATH }}
        run: |
          cd ./source
          dotnet tool restore
          dotnet docfx build
          rsync -avh ./_site ${USER_NAME}@${HOST_NAME}:${DEST_PATH}
