name: build-and-test
on: 
  push:
  pull_request:
    branches:
      - 'release'
      - 'main'


env: 
  DOTNET_VERSION: '6.0.400'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and Deply
        env:
            dest: ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }}:${{ secrets.PATH }}
        shell: bash
        run: |
          cd ./source
          dotnet tool restore
          dotnet docfx build
          echo "${{ secrets.PASSWORD }}" > deploy_key
          rsync \
            --exclude ./deploy_key
            --password-file ./deploy_key
            ./_site ${{ env.dest }}