name: build-and-test
on:
  push:
  pull_request:
    branches:
      - 'release'
      - 'main'


env:
  DOTNET_VERSION: '6.0.400'



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.HOST_NAME }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          TARGET: ${{ secrets.DEST_PATH }}
          SCRIPT_BEFORE: |
            cd ./source
            dotnet tool restore
            dotnet docfx build
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
